# The branch which all features will be merged into
default_branch: main

# The repository where issues will be created.
issues_repository:
  owner: ricardoamador
  repo: flutter_test

# The accounts that will have their changes auto-approved when opening a pull request.
auto_approval_accounts:
    - skia-flutter-autoroll,
    - engine-flutter-autoroll,
    - dependabot[bot]
    - dependabot
    - DartDevtoolWorkflowBot

# The number of approvals needed in order to merge a feature in the default branch.
approving_reviews: 1

# The group which will need to provide the reviews, currently OWNER and MEMBER in github.
approval_group: flutter-hackers

# Whether or not to run ci checks for each pull request.
run_ci: false

# Whether to allow revert pull requests to be merged without an approving review.
support_no_review_revert: false

# The required check runs that must complete before a pull request is merged.
required_checkruns:
    - “ci.yaml validation”

